stages:
  - staging

before_script:
  - eval $(ssh-agent -s)
  - chmod 600 $SSH_PRIVATE_KEY
  - /usr/bin/ssh-add $SSH_PRIVATE_KEY

deploy_staging:
  stage: staging
  script:
    - ssh $USER@$APP_URL_STAGING -o StrictHostKeyChecking=no ". restart_ssh.sh && /usr/bin/ssh-add .ssh/chatsapi && cd godmode && git pull origin develop && docker run -d build godmode && exit"
  only:
    - develop
  tags:
    - staging
