stages:
  - staging

# before_script:
#   - export PATH="$PATH:/usr/bin"

deploy_staging:
  stage: staging
  script:
    - echo $PATH
    - eval $(ssh-agent -s)
    - chmod 600 $SSH_PRIVATE_KEY
    - ssh-add $SSH_PRIVATE_KEY
    - ssh $USER@$APP_URL_STAGING -o StrictHostKeyChecking=no ". restart_ssh.sh && ssh-add .ssh/chatsapi && cd godmode && git pull origin develop && docker run -d build godmode && exit"
  only:
    - develop
  tags:
    - staging
