# stages:
#   - staging
#   - production

# before_script:
#   - eval $(ssh-agent -s)
#   - chmod 600 $SSH_PRIVATE_KEY
#   - ssh-add $SSH_PRIVATE_KEY 

# deploy_staging:
#   stage: staging
#   script:
#     # - eval $(ssh-agent -s)
#     # - chmod 600 $SSH_PRIVATE_KEY
#     # - ssh-add $SSH_PRIVATE_KEY
#     - ssh $USER@$APP_URL_STAGING -o StrictHostKeyChecking=no ". restart_ssh.sh && ssh-add .ssh/chatsapi && cd godmode && git checkout develop && git pull origin develop &&  docker-compose build && docker-compose up -d && exit"
#   only:
#     - develop
#   tags:
#     - staging

# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
image: node:16

stages:
  - test
  - build
  - deploy

sast:
  stage: test
include:
  - template: Security/SAST.gitlab-ci.yml

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist
    expire_in: 1 hour

deploy_staging:
  stage: deploy
  image: python:latest
  script:
    - apt-get update
    - apt-get -y install python3-pip
    - pip3 install awscli
    - aws s3 sync dist/ s3://$S3_BUCKET_STAGING --delete
  environment:
    name: staging
  only:
    - develop

deploy_production:
  stage: deploy
  image: python:latest
  script:
    - apt-get update
    - apt-get -y install python3-pip
    - pip3 install awscli
    - aws s3 sync dist/ s3://$S3_BUCKET --delete --region $AWS_REGION
  environment:
    name: production
  only:
    - production
