stages:
  - staging
  - production

before_script:
  - eval $(ssh-agent -s)
  - chmod 600 $SSH_PRIVATE_KEY
  - ssh-add $SSH_PRIVATE_KEY 

deploy_staging:
  stage: staging
  script:
    # - eval $(ssh-agent -s)
    # - chmod 600 $SSH_PRIVATE_KEY
    # - ssh-add $SSH_PRIVATE_KEY
    - ssh $USER@$APP_URL_STAGING -o StrictHostKeyChecking=no ". restart_ssh.sh && ssh-add .ssh/chatsapi && cd godmode && git checkout develop && git pull origin develop &&  docker-compose build && docker-compose up -d && exit"
  only:
    - develop
  tags:
    - staging
