stages:
  - staging


before_script:
  - export SSH_AUTH_SOCK=$(ssh-agent -a /tmp/ssh-agent.sock)
  - eval $(ssh-agent -s)
  - chmod 600 $SSH_PRIVATE_KEY
  - ssh-add $SSH_PRIVATE_KEY

deploy_staging:
  stage: staging
  script:
    - ssh $USER@$APP_URL_STAGING -o StrictHostKeyChecking=no ". restart_ssh.sh && ssh-add .ssh/chatsapi && cd godmode && git pull origin develop && docker run -d build godmode && exit"
  only:
    - develop
  tags:
    - staging
