version: "3.9"

services:
  dashboard:
    container_name: godmode
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3088:3088
    # networks:
    #   - gateway
    restart: unless-stopped

# networks:
#   gateway:
#     driver: bridge
